Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -17,6 +17,11 @@ jobs:
       with:
         node-version: '18'
 
+    - name: Debug file presence
+      run: |
+        ls -l
+        cat package.json || echo "package.json not found"
+
     - name: Install dependencies
       run: | 
          cd nodejs-demo-app
